name: Deploy to Cloudflare Workers

on: 
  workflow_dispatch:
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm install

      - name: Update package name
        run: node update-package-name.js
        env:
          PACKAGE_NAME: ${{ secrets.PACKAGE_NAME }}

      - name: Generate wrangler.toml
        run: node generate-wrangler-toml.js
        env:
          PACKAGE_NAME: ${{ secrets.PACKAGE_NAME }}

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: |
            BOT_TOKEN
            BOT_USERNAME
            EMOJI_LIST
            RESTRICTED_CHATS
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
          EMOJI_LIST: ${{ secrets.EMOJI_LIST }}
          RESTRICTED_CHATS: ${{ secrets.RESTRICTED_CHATS }}
